# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: taster.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='taster.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0ctaster.proto\"\x14\n\x04Note\x12\x0c\n\x04note\x18\x01 \x01(\t\" \n\x05Score\x12\x17\n\x0fpredicted_label\x18\x01 \x01(\x05\x32,\n\rMachineTaster\x12\x1b\n\x08getScore\x12\x05.Note\x1a\x06.Score\"\x00\x62\x06proto3')
)




_NOTE = _descriptor.Descriptor(
  name='Note',
  full_name='Note',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='note', full_name='Note.note', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=36,
)


_SCORE = _descriptor.Descriptor(
  name='Score',
  full_name='Score',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='predicted_label', full_name='Score.predicted_label', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=70,
)

DESCRIPTOR.message_types_by_name['Note'] = _NOTE
DESCRIPTOR.message_types_by_name['Score'] = _SCORE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Note = _reflection.GeneratedProtocolMessageType('Note', (_message.Message,), {
  'DESCRIPTOR' : _NOTE,
  '__module__' : 'taster_pb2'
  # @@protoc_insertion_point(class_scope:Note)
  })
_sym_db.RegisterMessage(Note)

Score = _reflection.GeneratedProtocolMessageType('Score', (_message.Message,), {
  'DESCRIPTOR' : _SCORE,
  '__module__' : 'taster_pb2'
  # @@protoc_insertion_point(class_scope:Score)
  })
_sym_db.RegisterMessage(Score)



_MACHINETASTER = _descriptor.ServiceDescriptor(
  name='MachineTaster',
  full_name='MachineTaster',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=72,
  serialized_end=116,
  methods=[
  _descriptor.MethodDescriptor(
    name='getScore',
    full_name='MachineTaster.getScore',
    index=0,
    containing_service=None,
    input_type=_NOTE,
    output_type=_SCORE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MACHINETASTER)

DESCRIPTOR.services_by_name['MachineTaster'] = _MACHINETASTER

# @@protoc_insertion_point(module_scope)
