# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import taster_pb2 as taster__pb2


class MachineTasterStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getScore = channel.unary_unary(
        '/MachineTaster/getScore',
        request_serializer=taster__pb2.Note.SerializeToString,
        response_deserializer=taster__pb2.Score.FromString,
        )


class MachineTasterServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getScore(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MachineTasterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getScore': grpc.unary_unary_rpc_method_handler(
          servicer.getScore,
          request_deserializer=taster__pb2.Note.FromString,
          response_serializer=taster__pb2.Score.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'MachineTaster', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
